# Use official Go image
FROM golang:1.24-alpine
# Install Air for live-reloading
RUN go install github.com/air-verse/air@v1.62.0
# Set working directory
WORKDIR /app
# Copy dependency files
COPY src/go.* .
# Download dependencies
RUN go mod download
# Copy source code
COPY src/ .
# Start air in development mode
CMD ["air", "-c", ".air.toml"]
