# Stage 1: Builder
FROM golang:1.24-alpine as builder
# Set working directory
WORKDIR /app
# Copy dependency files
COPY src/go.* ./
# Download dependencies
RUN go mod download
# Copy source code
COPY src/ ./
# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app

# Stage 2: Final Image
FROM alpine:3.22.0
# Set working directory
WORKDIR /app
# Copy the built binary from the builder stage
COPY --from=builder /go/bin/app .
# Runs the application
CMD ["./app"]
